# name: deploy to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure SSH
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$SSH_KEY" > ~/.ssh/ssh.key
#           chmod 600 ~/.ssh/ssh.key
#           cat >> ~/.ssh/config <<END
#             Host remote
#             HostName $HOST
#             User ubuntu
#             IdentityFile ~/.ssh/ssh.key
#             StrictHostKeyChecking no
#           END
#         env:
#           HOST: ${{ secrets.HOST }}
#           SSH_KEY: ${{ secrets.SSH_KEY }}
#       - name: Run remote SSH
#         env:
#           SCRIPT: /home/ubuntu/ureng-environment/portfolio.sh
#         run: |
#           echo "Running SSH deploy with $SCRIPT..."
#           DEPLOY_CMD=${SCRIPT}
#           echo "Branch is ${{ github.ref }}; Workflow is ${{ github.workflow }}"
#           ssh remote "/bin/bash -c '${DEPLOY_CMD} ${{ github.ref }}'"
#           if [ $? -ne 0 ]; then
#             echo "Error while running pipeline"
#             exit 255
#           fi
#           echo "Github Actions CI/CD pipeline completed"
